name: campus_connect
description: A social media app
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.5.0
  firebase_storage: ^10.0.2
  get: ^4.1.4
  http: ^0.13.3
  bot_toast: ^4.0.1
  shared_preferences: ^2.0.6
  path: ^1.8.0
  country_code_picker: ^2.0.1
  intl: ^0.17.0
  firebase_auth: ^3.0.2
  firebase_analytics: ^8.3.0
  image_picker: ^0.8.3+2
  cached_network_image: ^3.1.0
  cloud_firestore: ^2.5.0
  flutter_phone_direct_caller: ^2.0.0





dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Overpass
      fonts:
        - asset: assets/fonts/overpass/Overpass-Bold.ttf
          weight: 700
        - asset: assets/fonts/overpass/Overpass-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/overpass/Overpass-Regular.ttf
          weight: 400
        - asset: assets/fonts/overpass/Overpass-Light.ttf
          weight: 300
        - asset: assets/fonts/overpass/Overpass-Thin.ttf
          weight: 200
    - family: JosefinSlab
      fonts:
        - asset: assets/fonts/josefin/JosefinSlab-Bold.ttf
          weight: 700
        - asset: assets/fonts/josefin/JosefinSlab-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/josefin/JosefinSlab-Medium.ttf
          weight: 500
        - asset: assets/fonts/josefin/JosefinSlab-Regular.ttf
          weight: 400
        - asset: assets/fonts/josefin/JosefinSlab-Light.ttf
          weight: 300
        - asset: assets/fonts/josefin/JosefinSlab-Thin.ttf
          weight: 200
